[2022-03-14 02:50:06,092] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2022-03-14T02:48:50.278738+00:00 [queued]>
[2022-03-14 02:50:06,096] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2022-03-14T02:48:50.278738+00:00 [queued]>
[2022-03-14 02:50:06,101] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:50:06,108] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-14 02:50:06,109] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:50:06,117] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): storing_user> on 2022-03-14T02:48:50.278738+00:00
[2022-03-14 02:50:06,118] {standard_task_runner.py:52} INFO - Started process 14224 to run task
[2022-03-14 02:50:06,124] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'storing_user', '2022-03-14T02:48:50.278738+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjwg8mlr9', '--error-file', '/tmp/tmpwhaqdjpn']
[2022-03-14 02:50:06,124] {standard_task_runner.py:77} INFO - Job 28: Subtask storing_user
[2022-03-14 02:50:06,151] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.storing_user 2022-03-14T02:48:50.278738+00:00 [running]> on host airflowvm
[2022-03-14 02:50:06,178] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T02:48:50.278738+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T02:48:50.278738+00:00
[2022-03-14 02:50:06,178] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-03-14 02:50:06,178] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n.import /tmp/processed_user.csv users" | sqlite3 /home/airflow/airflow/airflow.db']
[2022-03-14 02:50:06,182] {subprocess.py:75} INFO - Output:
[2022-03-14 02:50:06,185] {subprocess.py:79} INFO - /tmp/processed_user.csv:1: INSERT failed: UNIQUE constraint failed: users.email
[2022-03-14 02:50:06,185] {subprocess.py:83} INFO - Command exited with return code 1
[2022-03-14 02:50:06,189] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-14 02:50:06,190] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20220314T024850, start_date=20220314T025006, end_date=20220314T025006
[2022-03-14 02:50:06,234] {local_task_job.py:151} INFO - Task exited with return code 1
