[2022-03-14 02:49:41,646] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-03-13T00:00:00+00:00 [queued]>
[2022-03-14 02:49:41,649] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-03-13T00:00:00+00:00 [queued]>
[2022-03-14 02:49:41,649] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:49:41,649] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-14 02:49:41,649] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:49:41,655] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-03-13T00:00:00+00:00
[2022-03-14 02:49:41,656] {standard_task_runner.py:52} INFO - Started process 14013 to run task
[2022-03-14 02:49:41,661] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2022-03-13T00:00:00+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp00fc092t', '--error-file', '/tmp/tmplbdgptf3']
[2022-03-14 02:49:41,662] {standard_task_runner.py:77} INFO - Job 21: Subtask is_api_available
[2022-03-14 02:49:46,690] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2022-03-13T00:00:00+00:00 [running]> on host airflowvm
[2022-03-14 02:49:46,722] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-03-14 02:49:46,722] {http.py:97} INFO - Poking: api/
[2022-03-14 02:49:46,725] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-03-14 02:49:46,727] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-14 02:49:47,054] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-14 02:49:47,057] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220313T000000, start_date=20220314T024941, end_date=20220314T024947
[2022-03-14 02:49:47,070] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-14 02:49:47,078] {local_task_job.py:151} INFO - Task exited with return code 0
